### ISSUE TITLE
consider defaulting to lower limit

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/NotesReview#1]
Or is downloading 3000 notes OK and not overloading OSM API?

**Comment by ENT8R** [comment]
If you open https://ent8r.github.io/NotesReview/ without any parameters, the default parameter for the limit will be 100. The [wiki](https://wiki.openstreetmap.org/wiki/API_v0.6#Search_for_notes_on_text_and_comments:_GET_.2Fapi.2F0.6.2Fnotes.2Fsearch) says for the `limit` parameter:

> A value of between 1 and 10000 is valid

If you set the limit to 3000 to see all open notes related to StreetComplete, it is noticable slower than setting it to 100. Do you have an idea how we can find out if huge limits are overloading the OSM API?

**Comment by matkoniecz** [comment]
I asked in https://github.com/openstreetmap/operations/issues/189 - I am not sure is it the best place to do that but I was unaware about anything better.

**Comment by matkoniecz** [comment]
If I interpreted response https://github.com/openstreetmap/operations/issues/189#issuecomment-355037563 correctly 

- one may test using dev server whatever this kind of query consumes too many resources
- it is OK to use it for now
- performance issues may result in modification of API and reducing valid limit
