### ISSUE TITLE
Deleted notes are visible in the app

### ISSUE THREAD

**Issue by starsep** [ENT8R/NotesReview#105]
Example:
https://osm.org/note/3023620

> http GET 'https://api.openstreetmap.org/api/0.6/notes/3023620'

410 Gone
The note with the id 3023620 has already been deleted

**Comment by danieldegroot2** [comment]
See https://github.com/ENT8R/notesreview-api/issues/1

**Comment by ENT8R** [comment]
Yep, this is already known and tracked in the linked issue
