### ISSUE TITLE
Save all settings of the filter

### ISSUE THREAD

**Issue by ppete2** [ENT8R/NotesReview#116]
Right now most settings of the filter are saved and loaded in the next session - good. But some are not, like From-date and To-date. Please save them too.

And another idea regarding filter: Please make its button distinguishable if a filter is set or using default values. Maybe by changing botton color

**Comment by ENT8R** [comment]
Thank you for reporting this bug.

Regarding your second idea: I added a small badge that shows the amount of filters that are a currently applied (excluding default values), so if the default values are being used, the badge disappears:
<div align="center"><img width="300px" src="https://github.com/ENT8R/NotesReview/assets/25306497/f7d4842b-8f74-43f8-8eda-14724a02b279"></div>
