### ISSUE TITLE
HTTP Error 500 from backend

### ISSUE THREAD

**Issue by GeorgeKaplan** [ENT8R/NotesReview#119]
Hi,

Backend replies with HTTP error 500. Every call returns this error after 30 sec :

$ time curl "https://notesreview.kongruent.xyz/api/search?query=existe&limit=100&status=open&sort_by=created_at"
⚠️ 500 — Internal Server Error
==============================
The application encountered an unexpected error and could not continue.

real	0m30.561s
user	0m0.027s
sys	0m0.019s

Any combination of parameters returns the same result.

**Comment by ENT8R** [comment]
I am sorry for the inconvenience, the server is running again as usual, need some more time to investigate why this happened in the first place

**Comment by GeorgeKaplan** [comment]
Thanks but it seems issue has come back today.

**Comment by ENT8R** [comment]
There seems to be an issue with updating existing notes. I will look into it later today, searching for existing notes should work again for now, but new notes and changes to existing notes can not be shown.

**Comment by ENT8R** [comment]
I think I found the issue (fixed with https://github.com/ENT8R/notesreview-api/commit/d9b87fe6ab32b5809c2cf824ba54d604736ca044) everything should work again.
