### ISSUE TITLE
"Image corrupt or truncated."

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#12]
As it can also be seen on https://github.com/ENT8R/NotesReview/issues/6#issuecomment-359909701, Firefox 57 always shows me in the dev console some images (tiis) would be corrupted.
I see no corrupted tiles on the website, but it's better to get rid of this annoying error message…

**Comment by rugk** [comment]
I noticed it does not happen for each tile displayed/loaded… it's rather random.

**Comment by ENT8R** [comment]
I can only reproduce this on Firefox and not with Chrome... I don't think that this is a real issue, it is rather a false-positive... According to https://help.openstreetmap.org/questions/5226/image-corrupt-or-truncated this happens only when you zoom in to fast... And I could also only reproduce this when I zoomed in very fast (with Firefox). Zooming slower does "fix" the issue...

**Comment by rugk** [comment]
Ah, okay, so does not really seem to be a way to hide these messages, as I see.
