### ISSUE TITLE
Cannot login -- does NotesReview need to implement OAuth2?

### ISSUE THREAD

**Issue by jmizv** [ENT8R/NotesReview#122]
Currently I have the problem that I cannot login on the NotesReview page.

Is this due to the deprecation of OAuth1: https://github.com/openstreetmap/operations/issues/867

**Comment by jmizv** [comment]
Sorry, now it works again. Thanks for checking.

**Comment by mmd-osm** [comment]
> As far as I know OAuth1 is still working and there is no explicit date for its deprecation

Meanwhile, a roadmap for shutting down OAuth 1.0a is available here: https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490

**Comment by ENT8R** [comment]
FYI, NotesReview now uses OAuth2 instead of OAuth1, so all users need to re-authenticate
