### ISSUE TITLE
Share the custom area in the URL

### ISSUE THREAD

**Issue by opk12** [ENT8R/NotesReview#124]
Thank you very much for this valuable tool. The Italian community would like to share a URL with a custom geometry filter (for the reasons described in #125). To make it possible, the shared URL should contain the geometry, so that the filter becomes usable on the receiving side.

**Steps to reproduce**
- Filter notes by a custom area.
- Click the Share button.
- The URL has `area=custom` and does not have the geometry.

**Comment by opk12** [comment]
What about a checkbox to make the full URL, even if unreadable? It will receive a custom label anyway, when it is posted in the chat as a link or saved in the browser bookmarks.

**Comment by ENT8R** [comment]
Sounds reasonable, I added an additional option in the share dialog now

**Comment by opk12** [comment]
Thank you. Could you give a less scary label to the checkbox? `May be unreadable` implies that *the app* may fail to parse the URL. `May be long` or `May be not human-readable` instead?

Or do not warn the user, he sees the URL anyway and will decide by themselves.

**Comment by opk12** [comment]
Thinking more about it, this is not a free choice. Could you make the checkbox non-interactive, and automatically checked / unchecked, depending on whether a custom area is used?

Because two meaningless choices are possible.
* If I filter by custom area, I can choose to not share it.
  * The URL will not work as expected.
  * It is the default in this case (unchecked by default), and should not be.
* If I do *not* filter by custom area, I can choose to share the custom area.
  * Luckily it has no effect, but IMHO does not make sense.

**Comment by ENT8R** [comment]
Thank you for staying persistent about this feature, really appreciate your feedback. I changed/improved a few things, like removing the warning regarding readability of the URL. Additionally, the checkbox for including the information is now opt-out and only shown if it would make sense (if there really is a custom drawn shape that could be shared).
