### ISSUE TITLE
Make showing the result amount permanently

### ISSUE THREAD

**Issue by jmizv** [ENT8R/NotesReview#127]
Sometime when the search results are loaded I do something else and when coming back later I have missed the information about the amount of search results.

Would it be possible to make the toast message either sticky when the page is not active or moving this information to a place in the header?

![image](https://github.com/ENT8R/NotesReview/assets/37914724/80f3b864-8cfe-4e0a-81c8-3d70b52988bc)

Filter is already showing `Filter ²` which means there are two filters active, right? Maybe the same works for `Show as List (61)`? Or a new label.

**Comment by ENT8R** [comment]
While I do not think this information is important enough to be shown all the time somewhere on the screen, I agree that it should still be shown once to the user. I changed the behavior, so the countdown to remove the toast message is only started when the window is currently in focus. Once you go back to the page the timer starts and you have 4s to see the information.

**Comment by jmizv** [comment]
> While I do not think this information is important enough to be shown all the time somewhere on the screen, I agree that it should still be shown once to the user. I changed the behavior, so the countdown to remove the toast message is only started when the window is currently in focus. Once you go back to the page the timer starts and you have 4s to see the information.

Thanks. I think this will be already enough for me :partying_face:
