### ISSUE TITLE
Broken image shown in notes list

### ISSUE THREAD

**Issue by jmizv** [ENT8R/NotesReview#128]
There are broken images shown:

![grafik](https://github.com/ENT8R/NotesReview/assets/37914724/a8baf9e2-0d35-4fa5-afe2-7cd7610a30c4)

Not sure what they originally mean.

**Comment by ENT8R** [comment]
They should show the flag of the country of the position of the note. The images fail to load because the CDN that was used has been shutdown, so I switched to the alternative jsDelivr instead.
