### ISSUE TITLE
Currently no notes show up ("CORS request did not succeed")

### ISSUE THREAD

**Issue by jmizv** [ENT8R/NotesReview#129]
Currently, I get no result for notes. Looking at the console of my web browser, I can see "CORS request did not succeed":

![grafik](https://github.com/ENT8R/NotesReview/assets/37914724/b59544ed-2769-4c2f-9c87-1c8ddf657a01)

**Comment by ENT8R** [comment]
Sorry for the inconvenience, the server was down a few hours ago and it is currently in the process of re-importing all notes as well as generating the database indices, so complex (text) searches are currently not possible. I will keep you updated here once everything is working again.

**Comment by ENT8R** [comment]
Everything should be working right now, if you notice something odd don't hesitate to contact me again
