### ISSUE TITLE
Find closed Note when search for open notes

### ISSUE THREAD

**Issue by Lurikbolding** [ENT8R/NotesReview#135]
summary : 
 - i search for open notes, but in the result, there is a closed note.

I made a search with NotesReview to find open notes.

I look around this point https://www.openstreetmap.org/note/4197324

I search with all value to default value:
 - search, author, user are empty
 - no date
 - **state = open**
 - anonymous = include
 - current view (north west paris)
 - commented = include.

in the result, the note nº 4197324 is show in the result

If i start to comment, the button "comment and close" is show

But if i show this note with osm.org, the note is visible but close since 6 month.

screen 1 : the search box
screen 2 : the map result
screen 3 : I can comment and close the note in NotesReview
screen 4 : the status of the note on osm.org
![1](https://github.com/user-attachments/assets/f29f66a4-4307-4dee-880c-f7e8741412df)
![2](https://github.com/user-attachments/assets/7ddcd029-a5dd-4c11-8bdc-f9c613fdda84)
![3](https://github.com/user-attachments/assets/6c938fa7-82b9-4ec6-9f40-46192fdf0044)
![4](https://github.com/user-attachments/assets/427b32e5-0670-4d02-9ec4-1ccdbe7e765b)

**Comment by ENT8R** [comment]
Thank you for reporting this issue. I reimported all notes into the database which should update all notes where the update mechanism failed in the past.
