### ISSUE TITLE
Pass turkey test

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#14]
As I said in [this PR](https://github.com/ENT8R/NotesReview/pull/13) that change does pass the turkey test.
See http://www.moserware.com/2008/02/does-your-code-pass-turkey-test.html for a whole article on it.

So I just wanted to open this issue to track this problem.

Maybe someone can try it out in turkey. 😄

**Comment by ENT8R** [comment]
Should be fixed with [`toLocaleUpperCase`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase)
