### ISSUE TITLE
Emulate notes request as StreetComplete does it

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#15]
I am trying to emulate the query, which StreetComplete uses to fetch the notes, respectively to display them, when the setting "Show all notes" is not enabled, i.e. when it only shows notes with a question mark (?) in it.

So I enter `?` in the search box. For some reason, this does only work in the fast (high zoom level) mode, not in the worldwide query. (I get the message that no notes are found then.)

BTW why did you remove the fast icon for high zoom levels? It was very helpful to see, when a fast query can be made.

**Comment by ENT8R** [comment]
> BTW why did you remove the fast icon for high zoom levels? It was very helpful to see, when a fast query can be made.

I didn't change there anything... For me it is still visible...

> So I enter ? in the search box. For some reason, this does only work in the fast (high zoom level) mode, not in the worldwide query.

That's strange... I will look if I can do something about that!

**Comment by ENT8R** [comment]
Mmhh... It looks like this is an issue of the OSM API... I tried several things to solve this, but all resulted in an empty answer...

**Comment by ENT8R** [comment]
The issue could be that the API can't handle URLs like this:
`https://api.openstreetmap.org/api/0.6/notes/search?q=?`
because there are two question marks which indicates normally the beginning of the URL parameters...

**Comment by ENT8R** [comment]
Also it is clear that it works for the high zoom level mode, because there is no query string specified...

**Comment by rugk** [comment]
Ah, I see. Could you try to HTML encode the question mark, i.e., `&#63;`? Or did you test that already?

**Comment by ENT8R** [comment]
Doesn't work either...

**Comment by ENT8R** [comment]
I tried again to find a solution to fix this, but I could not find anything. So this seems to be an unresolveable issue for now. If somebody has another idea how this might work, just write it here!

**Comment by rugk** [comment]
Can you somehow report it to the ones responsible for the notes API? Or do you know where to report such things?

As it just looks like an issue with their API…

**Comment by ENT8R** [comment]
True... I think the openstreetmap/openstreetmap-website repository is responsible for the API. I will open a new issue there.

**Comment by ENT8R** [comment]
Got a response in openstreetmap/openstreetmap-website#1781 and this is sadly not fixable...

**Comment by Lee-Carre** [comment]
Makes me wonder how @streetcomplete does it. I'd assume (read: guess) that it downloads all notes in the area, and filters locally. I recall that toggling the ‘show all notes’ (default is only questions) option *doesn't* trigger a rescan, only a redraw of what's displayed.

@westnordost ?

**Comment by westnordost** [comment]
Yes
