### ISSUE TITLE
Always shows NaN years old

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#23]
![image](https://user-images.githubusercontent.com/11966684/44308863-9fcda100-a3bd-11e8-9e11-5c037a13893f.png)

Console:
> Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (1829760 px). Occurrences of will-change over the budget will be ignored. NotesReview 

Firefox 63

**Comment by ENT8R** [comment]
Seems to be a bug which happens only on Firefox... I will investigate. Thank you for reporting it so fast 👍

**Comment by ENT8R** [comment]
Fixed it 🎉 The problem was that the date supplied by the OSM API was in an unparsable format for the date object.
