### ISSUE TITLE
Use date/badge color for marker

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#24]
From https://github.com/ENT8R/NotesReview/issues/19#issuecomment-414120722:
> There are now different badges with different colors for different ages of the notes.

Maybe you can color the note markers directly in the same way?

**Comment by ENT8R** [comment]
Looks like this now:
![screenshot](https://user-images.githubusercontent.com/25306497/44310846-5d1bc100-a3dd-11e8-928e-a94b2960f0b1.png)

**Comment by rugk** [comment]
Oh, looks great!

Are there only yellow and green?


---

Also, if we want to be consistent, it would be great to also have the "grouping" if multiple markers are in the same area, shown in the "average" of these colors or so. Or in the oldest/newest of the elements, whatever…

**Comment by ENT8R** [comment]
> Are there only yellow and green?

No there are all colors which are in the normal badges too (dark-green, orange, red,...)
Regarding your other idea: I will have to look what I can do and tell you then if something like this would be possible!
