### ISSUE TITLE
Filter does not apply to yellow and red notes

### ISSUE THREAD

**Issue by ray66** [ENT8R/NotesReview#30]
When a start is given only notes that have been created after this date should be displayed. However, notes that are displayed with a read or yellow icon an that are older than the start date are shown on the map.

**Comment by ENT8R** [comment]
Thank you for reporting this issue 👍
I just forgot to apply the filters also to the local/bounding box search. Using the global search everything should have worked.
The issue should now be fixed with https://github.com/ENT8R/NotesReview/commit/2ac019cfb86dd3c7b4879cc48f82ca25c998a18d
