### ISSUE TITLE
Feature request: Link to JOSM and iD

### ISSUE THREAD

**Issue by ray66** [ENT8R/NotesReview#31]
To process a note in JOSM or iD one has to click on "note xxx on OSM" and then on the edit button on osm.org. It would be nice to have a direct link to JOSM and iD in the note popup as have most other QA tools.

**Comment by ENT8R** [comment]
With the latest version of this tool, you can now select your favorite editors in the settings:
<div align="center">
    <img src="https://user-images.githubusercontent.com/25306497/59921084-e69c8500-942c-11e9-9cd4-68727573fd3b.png" width="600px">
</div>
