### ISSUE TITLE
Do not search in latest version

### ISSUE THREAD

**Issue by JorgeSanzS** [ENT8R/NotesReview#33]
I stopped working with the latest update. The search button does nothing.

**Comment by ENT8R** [comment]
Yes, I am currently working on fixing the issue. Sorry for the inconvenience.

**Comment by ENT8R** [comment]
Was easier to fix than I thought...
I hope you like the new version 😄

**Comment by JorgeSanzS** [comment]
It still does not work. Now you see a box on the map on the right, but you can not see the map either. The search still does not work.
I've already seen that you've added something like going directly to the editor. It was a necessary thing. The rest that I have not seen, I'm sure it's useful. 
Good job.

**Comment by ENT8R** [comment]
You are not using Internet Explorer, do you? Anyway, which browser and which version are you currently using?
Maybe it does also help to [clear your browser cache](https://www.refreshyourcache.com)

**Comment by JorgeSanzS** [comment]
I did not need to empty cache. It works now. Thank you

**Comment by ENT8R** [comment]
Great 🎉
BTW: thank you for your translations!
