### ISSUE TITLE
"osmauth.min.js" blocked by CORS

### ISSUE THREAD

**Issue by danstowell** [ENT8R/NotesReview#34]
Hi - the NotesReview page didn't work for me (nothing happening when I press "Search"). I noticed that I think the reason is my Firefox browser is blocking the loading of `osmauth.min.js` due to CORS security settings. I believe you need to add a CORS header `Access-Control-Allow-Origin`?

![cors](https://user-images.githubusercontent.com/202965/62197762-5b41d800-b378-11e9-88e3-ffd9223b2bd0.png)

**Comment by danstowell** [comment]
Same on Chromium

![cors2](https://user-images.githubusercontent.com/202965/62198074-e3c07880-b378-11e9-881d-6e40e25897f1.png)

**Comment by ENT8R** [comment]
Thank you for reporting the error so detailed 👍!
That's a real strange issue 🤔. A CDN who doesn't put a `Access-Control-Allow-Origin=*` in their header is not a real CDN 😄. And especially unpkg which is open to anybody should use this header, so I can't understand what triggered the error on your computer. I just tested it, and for me it works fine: There is a `Access-Control-Allow-Origin=*` in the header of the file and I can see the source code as a response...
What happens on your computer when you open https://unpkg.com/osm-auth@1.0.2/index.js ?

**Comment by danstowell** [comment]
Thanks for your reply! I think it must have been a temporary issue with the CDN, then - your site now works properly for me, with no changes here...

**Comment by ENT8R** [comment]
Alright 👍 I already thought it would be something like that 😄
Nevertheless, thank you for reporting it!
