### ISSUE TITLE
Hide anonymous notes

### ISSUE THREAD

**Issue by DaveF63** [ENT8R/NotesReview#36]
Checking/Unchecking 'Hide anonymous notes' causes the map to zoom in/out respectively*. Is this expected behaviour? 

In = 3 zoom factors
Out = zoom to almost world extents

Using Firefox latest on Win7
* Chrome causes the map o pan up & down slightly
  IE 10 won't even display the map window.

**Comment by ENT8R** [comment]
Currently the checking/unchecking of this checkbox is handled as a new search, so the map is adjusted that all markers fit on the screen.
I totally agree that this is not really useful especially if you zoomed in a lot and then check/uncheck this checkbox and the map moves/zooms for no real reason. I'm going to change this 😄
