### ISSUE TITLE
When note with 3 or more images is displayed, buttons on the bottom can become unaccessible, no scrolling, only panning map helps

### ISSUE THREAD

**Issue by xuiqzy** [ENT8R/NotesReview#41]
For example here https://www.openstreetmap.org/note/1842026 I first couldn't figure out how to fully see the buttons below (it works by panning the map). Instead it would be more intuitive to shrink the container for the note to the browser height and be able to scroll.

**Comment by ENT8R** [comment]
I totally agree... Thank you for bringing this to my attention 👍 I usually prefer to use the list view, so I don't test the map view a lot 😄

**Comment by ENT8R** [comment]
Up to 4 images are now displayed in a better way, but I probably have to think about a different solution, as there might still be some notes (maybe not that many) which include more than 4 images...
