### ISSUE TITLE
Comment button not working, comment applied to wrong note

### ISSUE THREAD

**Issue by arminus** [ENT8R/NotesReview#42]
At some point, adding a comment to a note and clicking the comment button didn't result in any visible feedback, i.e. the dialog window just continued to be visibly unmodified. Apparently, when opening another note after that, the comment button worked but applied the comment (and comment close) to the original note.

I'm 100% sure on the first click not having worked, less than 100% on the exact sequence of interaction on the 2nd issue. Is there some playground/test env where I could try to repro without having to create test/dummy notes in the live OSM db?

**Comment by ENT8R** [comment]
Sorry that I did not reply ealier, but I had a lot of other things to do in the last month...
I setup a testing instance for you at https://ent8r.lima-city.de/NotesReview-Test. You will need to create a new account at https://master.apis.dev.openstreetmap.org which is an official OpenStreetMap testing intance. You might create some new notes through the web interface before being able to see them at https://ent8r.lima-city.de/NotesReview-Test
I looked at the code again and I can't really find an issue regarding your explanation 🤷‍♂, so it would be really helpful if you could test it thoroughly and tell me how to reproduce it exactly 👍 Thank you already in advance 😄

**Comment by arminus** [comment]
I registered on https://master.apis.dev.openstreetmap.org/ but can't login on https://ent8r.lima-city.de/NotesReview-Test - this is what I get in thew console when clicking "Anmelden":

![2019-12-03_202429](https://user-images.githubusercontent.com/683680/70082636-24701d00-160b-11ea-9825-145b386fb583.png)

**Comment by ENT8R** [comment]
I think you need to refresh the page once after clicking login and it should work. I can't fix that minor issue currently, but it is nevertheless only an issue affecting the testing instance.

**Comment by arminus** [comment]
Ok, works after a refresh. I'll keep trying, no repro so far :-/

**Comment by arminus** [comment]
I'm afraid I can't reproduce the issue. I even pulled the network plug while a comment was open, still not able to observe any strange behavior anymore, the comments go to where they should go. So that's either a heisenbug or something was seriously wrong with my original observation :-/ Sorry for the maybe unnecessary effort...

**Comment by ENT8R** [comment]
No need to apologize 😄 If there would be a bug, it would be a quite severe one...
As I checked the code again and really could not find any issue regarding your observation, I propose to close this issue for now and if you encounter that bug again, reopen the issue.
