### ISSUE TITLE
False positive in search

### ISSUE THREAD

**Issue by tuxayo** [ENT8R/NotesReview#45]
As search for "camera" brings back this note which doesn't seems to have anything relevant.
https://www.openstreetmap.org/note/2083046#map=19/43.29558/5.37851

Is that expected?

**Comment by tuxayo** [comment]
More than half of the notes in the city come back when searching for "camera" and even more when searching for "example" and "test"

**Comment by ENT8R** [comment]
Thank you for reporting this bug! 
Are you zooming in, so that there appears a flash next in the search button?

**Comment by tuxayo** [comment]
Yes, it's a "flash search"

**Comment by tuxayo** [comment]
Thanks for the workaround :)

workaround: zoom at regional level before doing searches.

**Comment by ENT8R** [comment]
Alright, found the issue: I simply forgot to negate a statement when looking for the specified query in the local/fast mode when I refactored some code a few weeks ago 🙁...
Thank you very much for bringing this to my attention 👍

**Comment by tuxayo** [comment]
Thanks for the fix :D
