### ISSUE TITLE
Search shouldn't be sensitive to accents

### ISSUE THREAD

**Issue by tuxayo** [ENT8R/NotesReview#46]
Whether using the flash search or the normal search.

When I search for "caméra" or "camera" I get different results.

For example here: https://ent8r.github.io/NotesReview/?query=cam%C3%A9ra&map=16%2F43.2972%2F5.3814

**Comment by pyrog** [comment]
NotesReview "just" calling OSM API, and unfortunately the API don't have a parameter to ignore the case of the string to search (neither specify a regular expression).

See [Search for notes: GET /api/0.6/notes/search](https://wiki.openstreetmap.org/wiki/API_v0.6#Search_for_notes:_GET_.2Fapi.2F0.6.2Fnotes.2Fsearchhttps://wiki.openstreetmap.org/wiki/API_v0.6#Search_for_notes:_GET_.2Fapi.2F0.6.2Fnotes.2Fsearch)

**Comment by ENT8R** [comment]
While this is probably not that easily possible to fix for the global search (as this requires a change of the OpenStreetMap API), I could actually implement a fix so that it works at least in the local/flash mode, as this mode doesn't use the search endpoint of the API but instead downloads all notes in the area and filters them afterwards on the client side.

**Comment by tuxayo** [comment]
> NotesReview "just" calling OSM API

Upstream issue created: https://github.com/openstreetmap/openstreetmap-website/issues/2585

**Comment by ENT8R** [comment]
At least in the local search mode this is now fixed, as this requires separate handling nevertheless (https://github.com/ENT8R/NotesReview/commit/b137e521f1c61a6c47f652ac4e3308d62e02fadc)

**Comment by tuxayo** [comment]
Info from upstream https://github.com/openstreetmap/openstreetmap-website/issues/2585#issuecomment-612057369

> Generally speaking using the API for search is a bad idea and you're usually better off using third party services which specialise in that - we should probably get rid of all the search endpoints really.

**Comment by ENT8R** [comment]
With the switch to the new and improved backend, queries are now insensitive to accents and other diacritics under all circumstances 🎉

**Comment by Lee-Carre** [comment]
@ENT8R

> the new and improved backend, queries are now insensitive to accents and other diacritics

Only those cases, or full Unicode normalisation?

**Comment by ENT8R** [comment]
The query is both case and diacritic insensitive, but not normalized. So yes, only those two cases.
