### ISSUE TITLE
Map doesn't load

### ISSUE THREAD

**Issue by PanierAvide** [ENT8R/NotesReview#47]
Hello,

Map doesn't load, because there is some JS error :
```
Error: Set map center and zoom first. leaflet.js:5:40277
    _checkIfLoaded https://unpkg.com/leaflet@1.6.0/dist/leaflet.js:5
    getCenter https://unpkg.com/leaflet@1.6.0/dist/leaflet.js:5
    value https://ent8r.github.io/NotesReview/dist/js/main.min.js:1
    e https://ent8r.github.io/NotesReview/dist/js/main.min.js:1
    receiveMessage resource:///actors/BrowserTabChild.jsm:98
    wrapHandlingUserInput resource://gre/modules/E10SUtils.jsm:893
    receiveMessage resource:///actors/BrowserTabChild.jsm:95
```

Can be reproduced by clicking on "Show on a map", happens in Chromium or Firefox (latest version) under Arch Linux.

Best regards.

**Comment by ENT8R** [comment]
Weird, I have no problems when viewing the map... Could you maybe try to delete the local storage (in Firefox it should work like this: Shift + F9 -> right-click on local storage -> Delete all) and reload the page afterwards?

**Comment by PanierAvide** [comment]
Cleaning local storage makes effectively map working. Thanks for your feedback.
