### ISSUE TITLE
Provide a hint/link for search query syntax examples

### ISSUE THREAD

**Issue by bmillemathias-1a** [ENT8R/NotesReview#48]
The UI for the query field does not provide any help of the syntax expected nor the help, so I don't know what this field expects.

**Comment by pyrog** [comment]
There is no syntax 😉 
NotesReview call the OSM API to find notes.

See API doc: [Search for notes: GET /api/0.6/notes/search](https://wiki.openstreetmap.org/wiki/API_v0.6#Search_for_notes:_GET_.2Fapi.2F0.6.2Fnotes.2Fsearch)

**Comment by bmillemathias-1a** [comment]
A small icon (?) beside the field that explains that would be great

**Comment by ENT8R** [comment]
@pyrog Thank you for replying to this question, NotesReview is really just a simple front-end for the OpenStreetMap Notes API.
@bmillemathias-1a I'm not quite convinced why this would be needed, Google or other search engines also don't have a hint on how to use the query input field...

**Comment by pyrog** [comment]
@ENT8R like @bmillemathias-1a I thought that we could use a query language (i.e. with wildcards, regex…).
The term "_query_" sound like this 😉 

Of course when I understood that **NotesReview** is "just" a frond end to the API, I realize what query mean 😄 

Also, I started to translate your software in french, so it will help both french users 😆

@ENT8R how to test NotesReview locally ?

**Comment by pyrog** [comment]
> Google […] don't have a hint on how to use the query input field

There is a [sort of help page](https://www.google.com/advanced_search) about the syntax used by Google search 😉

**Comment by ENT8R** [comment]
Alright, makes sense. I will add something similar

**Comment by pyrog** [comment]
@ENT8R It could be a "simple" placeholder like _"words to search"_
