### ISSUE TITLE
add permalink creation option

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/NotesReview#5]
Permalinks like https://ent8r.github.io/NotesReview/?query=StreetComplete&limit=300 are quite useful.

Is it possible to add "create permalink to this query" and "create permalink to this query, execute search on loading page" options? Similar to what overpass-turbo offers?

**Comment by ENT8R** [comment]
Yes, this is useful!

**Comment by ENT8R** [comment]
Do you think it is enough to show this option in the help dialog? Otherwise it might be a little bit confusing...

**Comment by ENT8R** [comment]
There is now an option in the help dialog to create a permalink. You can also specify whether the query should start on page load.

**Comment by matkoniecz** [comment]
Thanks!
