### ISSUE TITLE
Add an option to display only notes with pictures

### ISSUE THREAD

**Issue by pyrog** [ENT8R/NotesReview#50]
So nice and useful to display **images** embedded in notes 🌞
Some [examples](https://ent8r.github.io/NotesReview/expert/?query=Attached%20photo(s)&anonymous=false).

Of course it could be a text query 😄

But could be fine to reuse the result of:
```javascript
function isImage(url)
```
… and have a simple checkbox 😄

**Comment by ENT8R** [comment]
What would be the advantage over the current behavior? I would like to keep the interface as minimalist and simple to use as possible. Sometimes, less options are much better than an overwhelming interface full of checkboxes and input fields for all possible use cases.

Furthermore, it would not be possible at the moment as the method you are referring to searches for occurrences of multiple image hosting servers, but as you know the OpenStreetMap Notes API does only allow to search for a single query per call...

**Comment by pyrog** [comment]
I appreciate also the KISS principle 😄 

What I suggest, is to **search** notes **the same way** (the API can't provide sophisticated query)…
…just **filter the result set** to hide notes without images detected by your software.

PS: In order to keep the interface simple, this filter could be a parameter added in the URL?

**Comment by ENT8R** [comment]
Mmhh... The amount of notes which actually have an image attached is drastically small, so this checkbox wouldn't make that much sense when using it without one of the keywords like "Attached photo(s)". And if "Attached photo(s)" is already the given query, then there are probably only notes which have an image attached to it, so I still don't quite see how this setting could be useful... 😞

**Comment by ENT8R** [comment]
As I already said, I don't think that having an option like you were proposing has an actual, useful usecase...
Unless you (or somebody else reading this) has another argument in favor of adding such an option, I would like to refrain from adding it.

**Comment by Lee-Carre** [comment]
@pyrog

A simpler alternative would be to *search for* URLs:

    ://

If you want more specific matches, such as images from specific sources, then be creative with your query 😉.
