### ISSUE TITLE
Date selector don't work under Safari

### ISSUE THREAD

**Issue by pyrog** [ENT8R/NotesReview#54]
Safari
<img width="533" alt="Date selector Safari" src="https://user-images.githubusercontent.com/2158081/78998138-455ff600-7b48-11ea-9afa-01459ff82e80.png">

Firefox
<img width="541" alt="Date selector Firefox" src="https://user-images.githubusercontent.com/2158081/78998136-44c75f80-7b48-11ea-972d-ebc89089c1b4.png">

**Comment by ENT8R** [comment]
I sadly don't have an access to a computer running on macOS, so I can't test it. Could you maybe make a screenshot of the javascript console output and post it here?

**Comment by pyrog** [comment]
**console**
```
[Info] [WDS] Live Reloading enabled. (vendors~main.min.js, line 1)
[Warning] [WDS] Warnings while compiling. (vendors~main.min.js, line 1)
[Warning] asset size limit: The following asset(s) exceed the recommended size limit (244 KiB). (vendors~main.min.js, line 1)
This can impact web performance.
Assets: 
  js/vendors~main.min.js (788 KiB)
[Warning] entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance. (vendors~main.min.js, line 1)
Entrypoints:
  main (836 KiB)
      js/vendors~main.min.js
      css/main.min.css
      js/main.min.js
```

**Comment by ENT8R** [comment]
Is this the output of the console after you clicked on the date input field?

**Comment by ENT8R** [comment]
Oh, nevermind, I just found out that Safari actually does not support a date picker for the date input field (see also https://caniuse.com/#feat=input-datetime). This is really strange, but nothing I could fix easily, except for using another completely different alternative than the default date input element 😞

**Comment by pyrog** [comment]
> I just found out that Safari actually does not support a date picker

May an issue in the date picker or in Safari ?

A simple workaround is to display a "localised" place holder.
`JJ/MM/AAAA`

**Comment by ENT8R** [comment]
This is an issue in Safari which does not support input fields with `input=date` in contrast to [all other major browsers](https://caniuse.com/#feat=input-datetime)...
Input fields with `input=date` will automatically show a date picker (except for Safari 😄), so there should not be the need for an additional library. I will think about how to give a hint to Safari users.
