### ISSUE TITLE
Share also the current note opened

### ISSUE THREAD

**Issue by pyrog** [ENT8R/NotesReview#55]
The display is fine in NotesReview 😺 

It could be nice to add also the note ID in the URL, and load and display automatically this note 😃 
[https://ent8r.github.io/NotesReview/expert/?note=2152730](https://ent8r.github.io/NotesReview/expert/?query=photo&closed=true&from=2020-04-08&to=2020-04-09&note=2152730)
[https://ent8r.github.io/NotesReview/?note=2152730](https://ent8r.github.io/NotesReview/?query=photo&closed=true&from=2020-04-08&to=2020-04-09&map=15%2F47.4641%2F-1.2806)

**Comment by ENT8R** [comment]
Displaying single notes is (currently) out of scope for this application, maybe I will change something in that regard in the future with another redesign of the interface. But that would likely take some time (if it's happening at all...)
For linking single notes, you should probably really better use the main OpenStreetMap website...
