### ISSUE TITLE
add portuguese language

### ISSUE THREAD

**Issue by eduaddad** [ENT8R/NotesReview#59]
add portuguese language

**Comment by ENT8R** [comment]
Hi @eduaddad 👋
Thank you very much for taking the time to translate NotesReview to Portuguese! I've been already notified by POEditor that you translated the strings, but I simply didn't push them to Github yet 😐. I'm currently doing this, so as soon as I push the commit to Github, NotesReview can also be used in Portuguese 🎉

**Comment by ENT8R** [comment]
Added with https://github.com/ENT8R/NotesReview/commit/c0810fed3fce60f06dedc4337e4ff0bb99d21a9a
