### ISSUE TITLE
Add an option to display only anonymous notes

### ISSUE THREAD

**Issue by pyrog** [ENT8R/NotesReview#60]
Some project allow anonymous notes.
They add hashtags to find easily them with i.e. NotesReview 😃 

It's easy to find [notes created by a specific user](https://ent8r.github.io/NotesReview/expert/?query=projetdumois&limit=1000&user=pyrog), but it's impossible to find **anonymous** notes.

**Comment by ENT8R** [comment]
Some time ago this was possible by searching for `anonymous` in the user input field, but this seems to be broken for some time...

**Comment by pyrog** [comment]
Did you repair it ?

It work now for "anonymous" user 😃
[Example](https://ent8r.github.io/NotesReview/expert/?query=projetdumois&limit=1000&user=anonymous).

**Comment by ENT8R** [comment]
Yes, with the latest commit, the search for anonymous notes work like that again.

**Comment by pyrog** [comment]
Thanks again 😎
