### ISSUE TITLE
URL is not clickable

### ISSUE THREAD

**Issue by pyrog** [ENT8R/NotesReview#61]
URL https://www.vosgesmatin.fr/faits-divers-justice/2020/10/02/un-defibrillateur-operationnel in this [note](https://ent8r.github.io/NotesReview/expert/?query=https%3A%2F%2Fwww.vosgesmatin.fr%2Ffaits-divers-justice%2F2020%2F10%2F02%2Fun-defibrillateur-operationnel).

<img width="33%" alt="Capture d’écran 2020-10-04 à 09 22 06" src="https://user-images.githubusercontent.com/2158081/95009548-305dae80-0623-11eb-9182-6c0ceef4f64b.png">

See https://github.com/vdct/ProjetDuMois/issues/74#issue-714255073

**Comment by pyrog** [comment]
Thank you 😃

**Comment by ENT8R** [comment]
Thank you for bringing this to my attention! The used library `linkify-it` does not seem to support these cases, so I decided to switch to `anchorme` which also supports more of these edge cases.
