### ISSUE TITLE
Map not shown with Firefox 81.0.2 (64-bit) on Windows

### ISSUE THREAD

**Issue by habi** [ENT8R/NotesReview#62]
When I go to https://ent8r.github.io/NotesReview/ with an up-to-date Firefox on Window, I don't see a map. My adblocker (uBlock Origin) is turned *off*.
Visiting the site with Google Chrome shows the map, as expected.

How can I help to debug this?

**Comment by rugk** [comment]
Are there any console messages?

**Comment by ENT8R** [comment]
Weird, I'm using the exact same version of Firefox too...

> How can I help to debug this?

Like @rugk already said it would be really helpful if you could provide a screenshot of the console (the window that shows up after pressing <kbd>F12</kbd>).
Otherwise you might also press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd> to open the network monitor, reload the page (<kbd>F5</kbd>) and look for HTTP status codes other than `200` in the very left column:
<div align="center"><img src="https://user-images.githubusercontent.com/25306497/96111631-bdd1b600-0ee1-11eb-9d2c-da2de5068e5c.jpg" width="600px"></div>

**Comment by habi** [comment]
> Are there any console messages? (F12)

```
Uncaught (in promise) Error: Set map center and zoom first.
    _checkIfLoaded Map.js:1287
    getCenter Map.js:833
    value main.min.js:1
    U main.min.js:1
    e main.min.js:1
    l vendors~main.min.js:1
    _invoke vendors~main.min.js:1
    m vendors~main.min.js:1
    o vendors~main.min.js:1
    s vendors~main.min.js:1
Map.js:1287:9

```

**Comment by habi** [comment]
> Otherwise you might also press Ctrl + Shift + E to open the network monitor, reload the page (F5) and look for HTTP status codes other than `200` in the very left column:

![Clipboard01](https://user-images.githubusercontent.com/1651235/96115647-92ea6080-0ee7-11eb-947b-f4965c7ec0bf.png)

**Comment by ENT8R** [comment]
I think I know what's wrong. Some time ago I updated the internal preference saving system and didn't pay enough attention to the fact that users already used the application before and this change obviously broke something 🤷

The following will likely fix it for you: visit the page and then press <kbd>Shift</kbd> + <kbd>F9</kbd> ➡️ right-click on local storage ➡️ Delete all

I'll leave this ticket open so I can eventually fix it permanently.

**Comment by habi** [comment]
> The following will likely fix it for you: visit the page and then press Shift + F9 arrow_right right-click on local storage arrow_right Delete all

The following *did* fix the issue, thanks for the pointer!

**Comment by ENT8R** [comment]
> I'll leave this ticket open so I can eventually fix it permanently.

This issue should only affect users which used the application between 20 June 2019 and 27 February 2020. Opening the application after the 27 February 2020 will then result in the same issue you described. Given that deleting the local storage is probably faster and easier (for me at least 😄) in contrast to implementing a permanent fix, I will (for now) change nothing regarding this issue.
