### ISSUE TITLE
Display Mapillary images with linkily.js

### ISSUE THREAD

**Issue by pyrog** [ENT8R/NotesReview#63]
Display image instead of Mapillary link like https://www.mapillary.com/map/im/ip8zserJnLUYUWDlZh1x6L.

See example in comments of [note 2394381](https://ent8r.github.io/NotesReview/expert/?query=Note%20de%20test%20avec%20%23photos%20et%20hashtags%20%23DAE).

**Comment by ENT8R** [comment]
Thank you for proposing this 👍 All links to Mapillary images should be converted to images now.

**Comment by pyrog** [comment]
Thank you very much 😎
