### ISSUE TITLE
'Search only in current view' doesn't use actual current view

### ISSUE THREAD

**Issue by JillisE** [ENT8R/NotesReview#69]
The new option Search only in current view uses the view that was present when the option is turned on.
When you e.g. zoom in on an area later on and click Search, you're being brought back to that view with its results.

The behaviour I'd expect is that clicking Search uses the view that's present at that moment, so I'm getting the result for the actual current view.
For that, I now have to zoom in first and *then* activate the option.

**Comment by ENT8R** [comment]
You're right, that's definitely not how it's supposed to be... Thank you very much for opening an issue, I will look into it 👍
