### ISSUE TITLE
Closing a note doesn't make it disappear anymore

### ISSUE THREAD

**Issue by JillisE** [ENT8R/NotesReview#70]
When I closed a note with a comment from the NotesReview GUI, it disappeared from my search results.
Now after the updates to the GUI/backend, it stays in the previous state: open and my comment isn't visible.
Clicking Search again doesn't help, only refreshing the browser (a.k.a. starting over) makes it disappear.

**Comment by ENT8R** [comment]
The comment should be visible again now after commenting a note, though it doesn't disappear yet in the case a user closed a note.

On the one hand, a closed note may not match the current query anymore and would not be displayed in the case of a new search, but on the other hand, the user who closed the note might want to add another comment to the closed note (i.e. reopening the note again and commenting on it).

I'm wondering which use case is more common and whether any of this might be unexpected behavior... Do you maybe have any thoughts/opinions on that @JillisE?

**Comment by JillisE** [comment]
Yes, I think reopening a note for a further comment should rarely happen, as it would be to correct a mistake in the previous comment or to add some forgotten text or clarification to it.
So it's ok if closed notes disappear like they used to, if you really need to get to it again, you can change the status filter to show all/closed notes.

**Comment by ENT8R** [comment]
You are probably right, fixed it with https://github.com/ENT8R/NotesReview/commit/28d0af666551e13c00af39bf77a5dbf8bdb56376
