### ISSUE TITLE
Highlight referenced geometry

### ISSUE THREAD

**Issue by westnordost** [ENT8R/NotesReview#72]
Sometimes, the note includes a link to the OSM element it refers to. It would be really cool if this element/geometry would be shown in some way when opening such note.

This probably requires to change the UI to show the note discussion next to the map instead of as a modal on top of the map. But I think it would make sense anyway to have the discussion in a sidebar because you often want to look at the map. After all, the note was created in context of the map.

# Mockup
![image](https://user-images.githubusercontent.com/4661658/120075722-bb078800-c0a2-11eb-8f7b-f468b266669c.png)

**Comment by westnordost** [comment]
The actual geometry (and tags) could be queried very easily with overpass. F.e.

```
[out:json];
way(id:54252257);
out geom tags;
```
http://overpass-turbo.eu/s/17Se

Maybe it makes sense to even show the tags somewhere.

**Comment by ENT8R** [comment]
Redesigning the note display was already on my list (the modal as a note comment display is just a temporary solution) and I will definitely keep your suggestion in mind 👍
I haven't really thought about this yet even though links to OpenStreetMap elements are already extracted from the comments...
Anyways, thank you for this excellent idea!

**Comment by ENT8R** [comment]
Geometries (except for nodes/points) mentioned in the authoring note comment are now highlighted using the default colors and style for now: 🎉

<img src="https://user-images.githubusercontent.com/25306497/120551203-0b118200-c3f6-11eb-8323-725a4769e52d.png">

**Comment by westnordost** [comment]
very cool!
