### ISSUE TITLE
Share current view ignored

### ISSUE THREAD

**Issue by Crashillo** [ENT8R/NotesReview#75]
When you share a map view, activating the share current view, you get the url with a `map=` parameter. Once you open a new tab in order to load that filtered view, all query params are gone, therefore the bounding box selected is not applied.

For instance, if I want to share this bounding box https://ent8r.github.io/NotesReview/?view=map&map=10%2F46.6226%2F9.5883&status=open, when you open this up you'll miss it, displaying different notes

**Comment by ENT8R** [comment]
Thank you for reporting this issue! If you want to share a query which searches only in the current view, there is now an additional URL parameter: `apply-bbox` which allows the recipient of the shared URL to display only the notes that are currently in the boundaries of the map view.
