### ISSUE TITLE
Map view should activate by default "search in the current view"

### ISSUE THREAD

**Issue by Crashillo** [ENT8R/NotesReview#76]
You start to zoom in, and then search, but the current view setting is unchecked so you get the full world notes. If you're at map view, such parameter should be active by default (if I remember that was the behaviour in the previous version)

https://user-images.githubusercontent.com/817526/127737077-abe364d3-d74b-4090-9a9d-3ba688e93ce0.mp4

**Comment by ENT8R** [comment]
I see that this can be confusing and the behavior was different before the API change, but I am unsure about whether this is a good idea to activate this by default. I only want to set default values where necessary, the users should decide what to filter on their own.

Adding to that, the previous implementation was already somewhat inelegant, as it switched between two different behaviors automatically, which was quite irritating for some users (especially if they did not know the meaning of the flash icon displayed next to the search button). And while this would be possible, I would not like to implement some kind of automatic switch (i.e. global search when zoomed out and local search when zoomed in) again for this reason.

What I could imagine is some kind of dialog asking the user if he wants to switch to the local search before the search is triggered, based on how much he zoomed in the map compared to the search before. Basically, the question asked would be something like "You have activated the global query, but zoomed in very far. Do you want to search only in the visible area or worldwide?"
Would this solve your problem too?

**Comment by Crashillo** [comment]
Still not convinced.

I you don't want to set defaults for each user, you could also store some settings in localStorage. If such settings are different from the default ones, you may highlight the Filter button, to make the user notice there's something changed.

But, as I said, the current behaviour is quite awkward. The website, by default, displays the map, centering the view with some "world" notes. IMHO, this is worthless. A OSM contributor is not interested in solving foreign notes, therefore is pretty likely the user zooms in/out on its region, then he clicks in search and boom! back again to world notes. Not user-friendly.
That's why I said, _search in the current view_ by default and not to do it, as a user choice option.

Your proposal could be annoying to the user: he plays with the zoom, searches, _do you wanna search global...?_, answers no, moves the view, searches again, _do you wanna search global...?_ no!

Actually, I didn't know there were two behaviours in the old implementation. I thought you're always fetching the notes in the current view, I believe that's the most accurate way to proceed when there is a bbox.

**Comment by pedjas** [comment]
I agree that it should search within current view by default. That is expected behavior. 

It is not obvious how to set search to current view. When I click on Search it zooms out and searches whole world. I cannot find  option to limit search to current view.

**Comment by Lee-Carre** [comment]
Why not save preferences to a cookie? Then everyone can have the behaviour they like.

**Comment by Lee-Carre** [comment]
Maybe, also, a go-to-my-location function might address some of the original concerns / complains, here?

**Comment by ArcaneDots** [comment]
1. I agree with @pedjas. Most OSM users tend to focus a single region at a time and expect to be able to limit the search accordingly. 
  2. It might be nice to auto-save the most recent search bbox in the cookie so it can be the user's default view next time the site is opened.

**Comment by ENT8R** [comment]
With the last commit, all queries are now persisted on your device between each session. This means of course that the information about the last query is restored when opening the page again.
I think this issue might be solved now, because with this change everybody should be able to set their own "defaults".
