### ISSUE TITLE
Why share window keeps making overpass queries?

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/NotesReview#84]
When I opened "share" window I noticed several overpass queries suddenly being made and failing. Why?
![screen01](https://user-images.githubusercontent.com/899988/145287060-3f2ef70a-fd43-4a13-8835-d1e3c29279ab.png)

**Comment by ENT8R** [comment]
Are you sure that this happens only when you open the share modal? Or are the error messages already displayed while reading notes on the map?
Overpass queries are only made if a reference to an OSM element is detected in the note text to show the corresponding geometry on the map.

**Comment by matkoniecz** [comment]
No, I am not really sure. Maybe appearance was a coincidence? Connections terminated just as I opened share window?

**Comment by matkoniecz** [comment]
Though maybe some limiting on side of note review page would be helpful?
