### ISSUE TITLE
Add a fool~~proof~~resistant way to filter to only StreetComplete notes

### ISSUE THREAD

**Issue by smichel17** [ENT8R/NotesReview#85]
In https://github.com/streetcomplete/StreetComplete/issues/3559#issuecomment-996104158, I mentioned that I think reviewing SC notes is the ideal way for SC users to transition to using other editors. Right now, you can search for "StreetComplete" in the query, but that's hard to get back to— if someone opens a new NotesComplete tab later, instead of following the url that pre-fills the query, they might not know how to get back to SC-only notes. A checkbox or something like that might be nice, even if it really just adds `StreetComplete` to the query.

**Comment by Lee-Carre** [comment]
What about saving preferences (like search terms) to a cookie?

**Comment by ENT8R** [comment]
Queries are now restored when reopening the page. If someone would open NotesReview via https://ent8r.github.io/NotesReview/?query=StreetComplete closes the tab after a while and then opens a new tab via https://ent8r.github.io/NotesReview/ the user will see the exact same result. I think this solves the described problem without adding an additional checkbox for this.
