### ISSUE TITLE
Version not displaying correctly on FAQ page

### ISSUE THREAD

**Issue by RayBB** [ENT8R/NotesReview#86]
Here's a screenshot:

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/921217/149863309-19992be0-7127-4771-8a9e-2f46476ec864.png">

**Comment by ENT8R** [comment]
Thank you for bringing this to my attention, fixed it with https://github.com/ENT8R/NotesReview/commit/6ad75ae2f34c808fb38a2e063f4b32e2c9c4cc60 right now 👍
