### ISSUE TITLE
In URLs generated for sharing, `[key]=null` is interpreted literally for `query` and/or `author`

### ISSUE THREAD

**Issue by Lee-Carre** [ENT8R/NotesReview#89]
Further to #88

> [an unmodified URL (copied from `share`, pasted as-is into the browser's URL bar)](//ent8r.github.io/NotesReview/?view=list&map=11%2F49.2%2F-2.1&query=null&apply-bbox=true&status=open&author=null&after=null&before=null); same failure-mode (**except for `null` being treated as a literal string for `query` and `author`, but that's a different glitch**).

[Emphasis added (here, not in the original).]

A simple way to avoid this would be to do as many other sites do, for empty-strings, and omit any value for that key:

    […]/?view=list&map=11%2F49.2%2F-2.1&query=&apply-bbox=true&status=open&author=&after=&before=

Better would be to omit the keys with null values, when generating the URL. Besides avoiding the problem, it's more succinct (and thus efficient).

**Comment by ENT8R** [comment]
Thank you for reporting this bug. Seems like this occurred since https://github.com/ENT8R/NotesReview/commit/7127e78168829ce3008346b1790cb9844ed51394 as I have not considered all effects of setting a value to `null`...

**Comment by Lee-Carre** [comment]
> Thank you for reporting this bug.

Welcome 🙂. NotesReview is proving most helpful in my surveying work. It's also pleasant to use (usability / UX); doesn't distract from surveying workflow. It's made my experience of handling notes much more efficient. I especially appreciate being able to find old *closed* notes. Lots of goodness. 👍👏

> Seems like this occurred since [`7127e78`](/ENT8R/NotesReview/commit/7127e78168829ce3008346b1790cb9844ed51394)

I did wonder if that commit was relevant. Good to know. 👨‍🎓

> I have not considered all effects of setting a value to `null`…

Perhaps a bit of Postel's Law needs be applied 🙂.
