### ISSUE TITLE
Map/header jumping when doing search

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#9]
The new cancel button looks nice, but I think it introduced this issue:

![jump](https://user-images.githubusercontent.com/11966684/35296434-4a3da102-007c-11e8-9830-0bcb4483d49b.gif)
webm file: [jump.zip](https://github.com/ENT8R/NotesReview/files/1657319/jump.zip)

As you can see, the height of the header is modified when the search happens. This is a visual annoyance.

**Comment by ENT8R** [comment]
Is the recording timelapse? And do you click all the time at the search/cancel button or only once?

**Comment by ENT8R** [comment]
OK. I found the issue. The map and the header shouldn't jump now anymore.
