### ISSUE TITLE
Export notes

### ISSUE THREAD

**Issue by matheusgomesms** [ENT8R/NotesReview#95]
Hi ENT8R,

Thank for the awesome work!

Just wondering, is there any possibility to export/download notes? In my case I would like to work in batch, or use another tool to better handle those notes.

Thanks!

**Comment by ENT8R** [comment]
Hi, sorry for the late response, I was really busy the last weeks.
If you want to query the backend directly to get the results of a search, you can find the documentation of the API at https://notesreview.kongruent.xyz/docs/swagger (but please note that this is still in an early stage and the parameters might be subject to change in the future without any notice)
Does this meet your requirements or have you thought of something else?

**Comment by matheusgomesms** [comment]
Hi ENT8R,

Thanks for the response! I was thinking more of a download button, on the frontend, so an user can export the displayed notes.

However, the link mentioned can be used as a temporary option.

**Comment by ENT8R** [comment]
I added a button in the sharing modal that allows to download the raw data of the currently displayed notes as a JSON file:

<img width="200px" src="https://github.com/ENT8R/NotesReview/assets/25306497/c9dfdde9-a46d-43b0-aac5-835eecb29b31">

**Comment by matheusgomesms** [comment]
Wow, wonderful, thanks a lot!!
