### ISSUE TITLE
Exclude users from results

### ISSUE THREAD

**Issue by Helium314** [ENT8R/NotesReview#97]
Currently it looks like the user filter is only able to find notes by specific users.
Sometimes it would also be very useful to *exclude* specific users from the results. Could this be added?

**Comment by ENT8R** [comment]
You are right that the user filter is currently inclusive and there is no possibility to exclude certain users. Could you tell me the specific use case you have in mind or why this could be useful? I can currently only think of excluding users who open a lot of notes in an area using them as their own personal todo list. While it would make sense to exclude these users from the results, I am not sure whether it is really worth adding another option...

**Comment by ENT8R** [comment]
This is now possible (see the FAQ):

> **Is it possible to search for multiple users?**
>
> Yes, by using a comma to separate each user.
> When searching for the author of a note, it will try to find notes that were opened by any of the given users.
> When searching for the users of a note, it will try to find notes that all of the given users commented on.
>
> **Is it possible to exclude certain users?**
> 
> Yes, by writing either <kbd>NOT</kbd> or <kbd>-</kbd> in front of the user to exclude.
> It is also possible to exclude multiple users by separating each user with a comma.

I decided to use this approach even though <kbd>NOT</kbd> or <kbd>-</kbd> are valid beginnings of OSM user names, and right now there are about 160 users starting with a dash <kbd>-</kbd> who commented on a note while there are no users that start with <kbd>NOT</kbd> and commented on a note. But I guess the convenience of typing a single (recognizable) character outweigh the fact that it is not possible to search for these users anymore.

**Comment by Helium314** [comment]
Thanks, that's really great!
